In [1]:
from keras.models import Sequential 
from keras.layers import Conv2D 
from keras.layers import MaxPooling2D 
from keras.layers import Flatten 
from keras.layers import Dense



from google.colab import drive
drive.mount('/content/gdrive')



Using TensorFlow backend.


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:

# Part 2 - Fitting the CNN to the images
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(   
    featurewise_center=False,
    samplewise_center=False,
    featurewise_std_normalization=False,
    samplewise_std_normalization=False,
    zca_whitening=False,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    vertical_flip=False)

test_datagen = ImageDataGenerator(rescale = 1./255)


training_set = train_datagen.flow_from_directory('/content/gdrive/My Drive/Colab Notebooks/train_data',
                                                 target_size = (64, 64),
                                                 batch_size = 16,
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory('/content/gdrive/My Drive/Colab Notebooks/test_data',
                                            target_size = (64, 64),
                                            batch_size = 16,
                                            class_mode = 'categorical')


Found 27 images belonging to 4 classes.
Found 9 images belonging to 4 classes.


In [10]:




# Initialising the CNN
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 1, activation = 'sigmoid'))
classifier.add(Dense(4, activation='softmax'))

# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

classifier.summary()

STEP_SIZE_VALID=test_set.n//test_set.batch_size

classifier.fit_generator(generator= training_set,
                         steps_per_epoch = 30,
                         epochs = 3,
                         validation_data = test_set,
                         validation_steps = 200
                        )

# 첫번째 인자 : 훈련데이터셋을 제공할 제네레이터를 지정합니다. 본 예제에서는 앞서 생성한 train_generator으로 지정합니다.
# steps_per_epoch : 한 epoch에 사용한 스텝 수를 지정합니다. 총 45개의 훈련 샘플이 있고 배치사이즈가 3이므로 15 스텝으로 지정합니다.
# epochs : 전체 훈련 데이터셋에 대해 학습 반복 횟수를 지정합니다. 100번을 반복적으로 학습시켜 보겠습니다.
# validation_data : 검증데이터셋을 제공할 제네레이터를 지정합니다. 본 예제에서는 앞서 생성한 validation_generator으로 지정합니다.
# validation_steps : 한 epoch 종료 시 마다 검증할 때 사용되는 검증 스텝 수를 지정합니다. 홍 15개의 검증 샘플이 있고 배치사이즈가 3이므로 5 스텝으로 지정합니다.

   

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_15 (Conv2D)           (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_8 (Flatten)          (None, 6272)              0         
_________________________________________________________________
dense_18 (Dense)             (None, 128)               802944    
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 129       
__________

In [11]:

# 모델 평가

scores = classifier.evaluate_generator(
            test_set, 
            steps = 5)

print("%s: %.2f%%" %('Accuracy', scores[1]*100))

Accuracy: 44.44%


In [12]:
import numpy as np
# 모델 예측하기
print("-- Predict --")


output = classifier.predict_generator(
            test_set, 
            steps = 5)

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(output)

-- Predict --
[[0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 0.221 0.254]
 [0.382 0.143 